module.exports = {
  extends: ['stylelint-config-standard', 'stylelint-config-prettier'],
  plugins: [
    'stylelint-scss',
    'stylelint-prettier',
    'stylelint-declaration-block-no-ignored-properties',
  ],
  customSyntax: 'postcss-scss',
  rules: {
    'declaration-block-no-duplicate-properties': true,
    'function-name-case': [
      'lower',
      {
        ignoreFunctions: ['/colorPalette/'],
      },
    ],
    'no-invalid-double-slash-comments': null,
    'no-descending-specificity': null,
    'declaration-empty-line-before': null,
    'comment-empty-line-before': null,
    'declaration-colon-newline-after': null,
    'at-rule-no-unknown': null,
    'scss/at-rule-no-unknown': true,
    'scss/declaration-nested-properties': 'never',
    'scss/selector-no-redundant-nesting-selector': true,
    'scss/percent-placeholder-pattern': '^do-not-use-placeholders$',
    'scss/at-mixin-named-arguments': 'always',
    'scss/dollar-variable-no-missing-interpolation': true,
    'scss/at-mixin-argumentless-call-parentheses': 'always',
    'scss/media-feature-value-dollar-variable': 'always',
    'scss/no-duplicate-dollar-variables': true,
    'scss/no-duplicate-mixins': true,
    'scss/function-unquote-no-unquoted-strings-inside': true,
    'scss/function-quote-no-quoted-strings-inside': true,
    'scss/dimension-no-non-numeric-values': true,
    'scss/comment-no-loud': true,
    'scss/at-import-partial-extension': 'never',
    'scss/at-if-no-null': true,
    'scss/at-each-key-value-single-line': true,
    'function-no-unknown': null,
    'value-keyword-case': null,
    'no-invalid-position-at-import-rule': null,
    'length-zero-no-unit': null,
  },
  ignoreFiles: [],
};
